r"""
Build the SCENE_PLAN prompt for one episode: exactly 20 scene beats,
using that episode's entry from episode_outline (already generated by
the series-planning bootstrap) as the source of truth for what this
episode covers and who's in it.

Usage:
    python generate_scene_plan_prompt.py PROJECT_ID EPISODE_NUMBER

Writes GLM_Scene_Plan_Prompt.txt, ready for:
    python run_glm_prompt.py GLM_Scene_Plan_Prompt.txt
    python load_story_to_db.py outputs/GLM_Test_Output.json PROJECT_ID
"""

import json
import sys
from pathlib import Path

import mysql.connector

# Reuse the same DB_CONFIG / fetch_bibles / fetch_episode_outline logic
# already written and tested in generate_episode_prompt.py, rather than
# duplicating it.
from generate_episode_prompt import DB_CONFIG, fetch_bibles, fetch_episode_outline


def build_prompt(project_id: str, episode_number: int) -> str:
    conn = mysql.connector.connect(**DB_CONFIG)
    cursor = conn.cursor()
    try:
        outline = fetch_episode_outline(cursor, project_id, episode_number)
        if not outline:
            raise SystemExit(
                f"No episode_outline entry found for episode {episode_number} of '{project_id}'. "
                f"Run generate_bootstrap_prompt.py (SERIES_OUTLINE) first."
            )
        bibles = fetch_bibles(cursor, project_id, outline["character_ids"], outline["location_ids"])
    finally:
        cursor.close()
        conn.close()

    parts = []
    parts.append('Use stage "SCENE_PLAN".')
    parts.append("")
    parts.append(f"Project: {project_id}, Episode {episode_number} ({outline['episode_id']}).")
    parts.append("")
    parts.append(f"EPISODE TITLE: {outline['title']}")
    parts.append(f"EPISODE SUMMARY (from the series outline — this is what this episode must cover): {outline['summary']}")
    parts.append("")
    parts.append("The following is REFERENCE CONTEXT ONLY (only what's relevant to this episode). "
                  "Do not repeat it in your output, reference by ID only.")
    parts.append("")
    parts.append("CHARACTERS in this episode (reference):")
    parts.append(json.dumps(bibles["characters"], ensure_ascii=False))
    parts.append("")
    parts.append("LOCATIONS in this episode (reference):")
    parts.append(json.dumps(bibles["locations"], ensure_ascii=False))
    parts.append("")
    parts.append(
        f"TASK: Produce exactly 4 scene_plan entries for episode {outline['episode_id']} "
        f"(scene_id format: {outline['episode_id']}_SC_01 through {outline['episode_id']}_SC_04). "
        "Cover the episode summary above with real narrative pacing across the 4 scenes."
    )
    parts.append("")
    parts.append("Return only the JSON object as defined by your output contract. No prose, no markdown fences.")

    return "\n".join(parts)


def main():
    if len(sys.argv) != 3:
        print("Usage: python generate_scene_plan_prompt.py PROJECT_ID EPISODE_NUMBER")
        sys.exit(1)

    project_id = sys.argv[1]
    episode_number = int(sys.argv[2])

    prompt = build_prompt(project_id, episode_number)
    out_path = Path("GLM_Scene_Plan_Prompt.txt")
    out_path.write_text(prompt, encoding="utf-8")
    print(f"Wrote {out_path} ({len(prompt)} chars) for episode {episode_number}.")


if __name__ == "__main__":
    main()
