'use strict';
const $ = id => document.getElementById(id);
let dashboard = null, promptRows = [], selectedPrompt = null, computedSpec = null, computedPrompt = '', runId = null, refreshing = false, latestReviewSignature = '';
const labels = {character_reference:'Character reference',location_reference:'Location reference',prop_reference:'Prop reference',shot_image:'Shot image',shot_video:'Shot video',final_render:'Episode export'};
function notify(text,error=false){$('notice').hidden=!text;$('notice').textContent=text;$('notice').className=error?'error':'';}
function errorText(detail){if(Array.isArray(detail))return detail.map(e=>`${e.loc?.slice(1).join(' · ')||'Settings'}: ${e.msg}`).join('\n');return typeof detail==='string'?detail:'The request could not be completed.';}
async function api(path,body,method='POST'){const response=await fetch(path,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data;try{data=await response.json()}catch{throw Error(`Gateway returned HTTP ${response.status}. Check the gateway log for the cause.`)}if(!response.ok)throw Error(errorText(data.detail));return data;}
function base(){const id=$('project').value;if(!id)throw Error('Create or select a production first.');return '/projects/'+encodeURIComponent(id);}
function tab(name){for(const panel of document.querySelectorAll('.panel'))panel.hidden=panel.id!==name;for(const button of document.querySelectorAll('[data-tab]'))button.classList.toggle('selected',button.dataset.tab===name);if(name==='prompts'&&$('project').value)loadPrompts().catch(e=>notify(e.message,true));if(['review','exports'].includes(name)&&$('project').value)loadAssets().catch(e=>notify(e.message,true));}
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>tab(button.dataset.tab);
function settings(){return {project_id:$('projectId').value.trim(),title:$('title').value.trim(),concept:$('concept').value.trim(),episodes:Number($('episodes').value),scenes_per_episode:Number($('scenes').value),shots_per_scene:Number($('shots').value),episode_seconds:Math.round(Number($('minutes').value)*60),characters:Number($('characters').value),locations:Number($('locations').value),visual_style:$('style').value.trim(),direction:$('direction').value.trim(),image_model_key:$('imageModel').value,video_model_key:$('videoModel').value,lora_mode:$('loraMode').value,lora_name:$('loraName').value,lora_strength:Number($('loraStrength').value),review_mode:$('reviewMode').value};}
function runtime(){const shots=Number($('scenes').value)*Number($('shots').value),seconds=Math.round(Number($('minutes').value)*60),low=Math.floor(seconds/shots),high=Math.ceil(seconds/shots);const valid=shots>0&&low>=2&&high<=20;$('runtime').classList.toggle('invalid',!valid);$('runtime').textContent=valid?`${shots} shots per episode · ${seconds} seconds total · ${low===high?low:low+'–'+high} seconds per shot. The planner assigns exact shot durations.`:`Choose enough shots for the runtime: each shot must be 2–20 seconds. For ${shots||0} shots, use ${(shots*2/60).toFixed(2)}–${(shots*20/60).toFixed(2)} minutes.`;}
$('title').addEventListener('input',()=>{if(!$('projectId').dataset.manual){let slug=$('title').value.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');if(slug&&!/^[a-z]/.test(slug))slug='film_'+slug;$('projectId').value=slug.slice(0,32);}});
$('projectId').oninput=()=>$('projectId').dataset.manual='true';
$('setupForm').addEventListener('input',()=>{runtime();if(computedSpec){computedSpec=null;$('generatePlan').disabled=true;$('planSummary').textContent='Settings changed. Compute the prompt again to match the new production.';}});
$('loraMode').onchange=()=>$('customLora').hidden=$('loraMode').value!=='custom';
$('videoModel').onchange=()=>{if($('videoModel').value==='ltx-2.5'&&$('loraMode').value==='template'){$('loraMode').value='none';notify('MiniMax template LoRA does not apply to LTX. Select a compatible installed LoRA if needed.');}};
$('setupForm').onsubmit=async event=>{event.preventDefault();$('compute').disabled=true;try{const spec=settings(),result=await api('/productions/preview',spec);computedSpec=spec;computedPrompt=result.prompt;$('bootstrapPrompt').value=result.prompt;$('bootstrapPrompt').disabled=false;$('planSummary').textContent=`${result.summary} ${result.estimated_model_calls} local planning calls.`;for(const id of ['generatePlan','improveOutline','restoreOutline'])$(id).disabled=false;notify('Prompt computed. Read or edit it, then generate the production plan.');}catch(e){notify(e.message,true)}finally{$('compute').disabled=false}};
$('restoreOutline').onclick=()=>$('bootstrapPrompt').value=computedPrompt;
async function suggest(editor,instruction,target,container,button){button.disabled=true;const previous=button.textContent;button.textContent='Thinking locally…';try{const result=await api('/prompts/improve',{prompt:$(editor).value,instruction:$(instruction).value||'Make this prompt specific, cinematic and clear. Preserve all facts, stage instructions, IDs, counts and runtime requirements.'});$(target).value=result.prompt;$(container).hidden=false;notify('Suggestion ready. Your original prompt is unchanged until you choose this version.');}catch(e){notify(e.message,true)}finally{button.textContent=previous;button.disabled=false}}
$('improveOutline').onclick=()=>suggest('bootstrapPrompt','outlineInstruction','suggestedOutline','outlineSuggestion',$('improveOutline'));
$('applyOutline').onclick=()=>{$('bootstrapPrompt').value=$('suggestedOutline').value;$('outlineSuggestion').hidden=true};
$('generatePlan').onclick=async()=>{if(!computedSpec)return;const button=$('generatePlan');button.disabled=true;try{const run=await api('/productions',{...computedSpec,bootstrap_prompt:$('bootstrapPrompt').value});runId=run.id;await loadProjects(computedSpec.project_id);tab('production');notify('Local planning started. You can follow progress here; the browser can be closed without stopping it.');}catch(e){notify(e.message,true)}finally{button.disabled=!computedSpec}};
$('newProject').onclick=()=>{computedSpec=null;$('setupForm').reset();$('projectId').dataset.manual='';$('bootstrapPrompt').value='';$('bootstrapPrompt').disabled=true;for(const id of ['generatePlan','improveOutline','restoreOutline'])$(id).disabled=true;$('planSummary').textContent='Fill in the idea and compute the prompt to begin.';$('outlineSuggestion').hidden=true;$('customLora').hidden=true;runtime();tab('setup');notify('Create a new production. Your existing projects remain available in the selector.');};
async function loadProjects(preferred){const result=await api('/projects'),old=preferred||$('project').value;$('project').replaceChildren();for(const project of result.projects){const option=document.createElement('option');option.value=project.project_id;option.textContent=project.project_id;$('project').append(option)}if(!result.projects.length){const option=document.createElement('option');option.value='';option.textContent='Create your first production';$('project').append(option)}else if(result.projects.some(p=>p.project_id===old))$('project').value=old;await refresh();}
async function refresh(){if(refreshing||!$('project').value)return;refreshing=true;try{dashboard=await api(base()+'/production');const state=dashboard.settings,planning=state?.planning_status;$('progressTitle').textContent=planning==='running'?'Building your story':dashboard.next_action==='complete'?'Production complete':state?.automation_enabled?'Automatic production is on':'Your production workspace';$('progressMessage').textContent=dashboard.message+(planning==='running'&&state?.planning_stage?' Current step: '+state.planning_stage.replaceAll('_',' ')+'.':'');$('nextStep').textContent=dashboard.message+(state?.automation_enabled?' The system continues automatically when reviews are resolved.':'');$('startAuto').disabled=!state||planning!=='ready'||!state.prompts_approved;$('startAuto').hidden=Boolean(state?.automation_enabled);$('pauseAuto').hidden=!state?.automation_enabled;$('approvePrompts').disabled=!state||planning!=='ready'||dashboard.worker_busy||Boolean(state.automation_enabled);$('pauseForPrompts').hidden=!state?.automation_enabled;$('resumePlanning').hidden=!(state&&['failed','pending','running'].includes(planning)&&!dashboard.worker_busy);$('resumePlanning').textContent=planning==='running'?'Resume interrupted planning':'Resume failed planning';$('advanceOnce').disabled=dashboard.worker_busy||!['continue','review'].includes(dashboard.next_action);renderStages(dashboard);renderFailures(dashboard);$('episode').replaceChildren();for(const ep of dashboard.episodes){const option=document.createElement('option');option.value=option.textContent=ep.episode_id;$('episode').append(option)}
const completed=state?.completed?.length||0,total=state?1+state.spec.episodes*(1+state.spec.scenes_per_episode):1;$('planProgress').hidden=!state||planning==='ready';$('planProgress').max=total;$('planProgress').value=completed;
if(!runId&&dashboard.runs.length&&dashboard.runs[0].status==='running')runId=dashboard.runs[0].id;
if(!runId&&dashboard.runs.length){$('runLabel').textContent=`${dashboard.runs[0].worker} · ${dashboard.runs[0].status}`;}
const signature=JSON.stringify(dashboard.reviews)+$('project').value;if(signature!==latestReviewSignature){latestReviewSignature=signature;await loadAssets();}
}catch(e){notify(e.message,true)}finally{refreshing=false}}
function renderStages(data){$('stageCards').replaceChildren();const groups=[['Story plan',[],data.settings?.completed?.length||0],['References',['character_reference','location_reference','prop_reference']],['Shot images',['shot_image']],['Video clips',['shot_video']],['Final exports',[]]];groups.forEach(([name,types,planning],index)=>{const card=document.createElement('div');card.className='card stage';const step=document.createElement('div');step.className='step-number';step.textContent='STAGE '+(index+1);const heading=document.createElement('h3');heading.textContent=name;const amount=document.createElement('div');amount.className='count';const jobs=data.jobs.filter(j=>types.includes(j.job_type));const done=jobs.filter(j=>j.status==='done').reduce((sum,j)=>sum+j.count,0),total=jobs.reduce((sum,j)=>sum+j.count,0);amount.textContent=index===0?(data.settings?.planning_status==='ready'?'Ready':planning+' steps'):index===4?data.episodes.length+' episodes':done+' / '+total;const hint=document.createElement('p');hint.textContent=index===0?'Bible, scenes and prompts':index===4?'Assembled after clip approval':jobs.some(j=>j.status==='running')?'Generating locally / via API':jobs.some(j=>j.status==='failed')?'Needs attention':'Generated / queued';card.append(step,heading,amount,hint);$('stageCards').append(card)});}
function renderFailures(data){$('failures').hidden=!data.failures.length;$('failures').replaceChildren();if(!data.failures.length)return;const h=document.createElement('h3');h.textContent='Jobs that need attention';$('failures').append(h);for(const job of data.failures){const row=document.createElement('div');row.className='failure-row';const text=document.createElement('p');text.textContent=`#${job.id} · ${labels[job.job_type]||job.job_type} · ${job.status}\n${job.error||'Running. An interrupted render may still be processing externally.'}`;row.append(text);if(job.status==='failed'){const b=document.createElement('button');b.className='secondary';b.textContent='Retry this job';b.disabled=data.worker_busy;b.onclick=async()=>{try{await api(base()+`/jobs/${job.id}/retry`,{});notify('Job queued again. Automatic mode resumes when ready. Check a video submission’s saved ComfyUI prompt before resubmitting.');await refresh()}catch(e){notify(e.message,true)}};row.append(b)}$('failures').append(row)}}
async function loadPrompts(){const [data,story]=await Promise.all([api(base()+'/prompts'),api(base()+'/story')]);$('storyOutline').replaceChildren();const premise=document.createElement('p');premise.textContent=story.bible.logline||story.bible.premise||'Story data is still being planned.';$('storyOutline').append(premise);for(const episode of story.outline){const h=document.createElement('h3'),p=document.createElement('p');h.textContent=`Episode ${episode.episode_number}: ${episode.title}`;p.textContent=episode.summary;$('storyOutline').append(h,p)}promptRows=[...data.prompts,...data.video_prompts.filter(v=>!data.prompts.some(j=>j.job_type==='shot_video'&&j.shot_id===v.shot_id)).map(v=>({...v,job_type:'shot_video',status:'planned',kind:'video_plan'}))];renderPromptList();}
function renderPromptList(){const filter=$('promptFilter').value;$('promptList').replaceChildren();const rows=promptRows.filter(p=>filter==='all'||(filter==='references'?p.job_type.endsWith('_reference'):p.job_type===filter));if(!rows.length){empty($('promptList'),'Prompts appear after the story plan is generated.');return}for(const row of rows){const b=document.createElement('button');b.textContent=labels[row.job_type]||row.job_type;const detail=document.createElement('small');detail.textContent=`${row.shot_id||row.scene_id||'#'+row.id} · ${row.status}`;b.append(detail);b.onclick=()=>{for(const item of $('promptList').children)item.classList.remove('selected');b.classList.add('selected');selectedPrompt=row;$('promptTitle').textContent=labels[row.job_type]||row.job_type;$('promptStatus').textContent=row.status;$('jobPrompt').value=row.prompt||'';const editable=['queued','failed','planned'].includes(row.status)&&!dashboard?.worker_busy&&!dashboard?.settings?.automation_enabled;$('promptReferences').disabled=!editable||row.kind==='video_plan';$('renderPrompt').disabled=!editable||row.status!=='queued'||row.kind==='video_plan';$('jobPrompt').disabled=!editable;$('savePrompt').disabled=!editable;$('improvePrompt').disabled=!editable;$('jobSuggestion').hidden=true;$('promptHint').textContent=editable?'Changes affect the next render. Save before continuing production.':(['queued','failed','planned'].includes(row.status)?'Pause automatic production and wait for the current worker to edit this prompt.':'This prompt has already been used. Open its asset in Review and create an edited version; approval does not lock editing.')};$('promptList').append(b)}}
$('promptFilter').onchange=renderPromptList;
$('savePrompt').onclick=async()=>{if(!selectedPrompt)return;try{await api(base()+(selectedPrompt.kind==='video_plan'?'/shots/'+encodeURIComponent(selectedPrompt.shot_id)+'/video-prompt':`/jobs/${selectedPrompt.id}/prompt`),{prompt:$('jobPrompt').value},'PUT');selectedPrompt.prompt=$('jobPrompt').value;notify('Prompt saved. The next render uses this version.');}catch(e){notify(e.message,true)}};
$('improvePrompt').onclick=()=>suggest('jobPrompt','promptInstruction','suggestedJob','jobSuggestion',$('improvePrompt'));
$('applyJob').onclick=()=>{$('jobPrompt').value=$('suggestedJob').value;$('jobSuggestion').hidden=true;notify('Suggestion copied into the editor. Save it before rendering.')};
async function automation(enabled,approve=false,target='production'){try{const result=await api(base()+'/automation',{enabled,approve_prompts:approve});notify(result.message);await refresh();tab(target)}catch(e){notify(e.message,true)}}
$('approvePrompts').onclick=()=>automation(true,true);$('startAuto').onclick=()=>automation(true);$('pauseAuto').onclick=()=>automation(false);$('pauseForPrompts').onclick=()=>automation(false,false,'prompts');
async function runWorker(worker,options={}){try{const run=await api(base()+'/workers/'+worker,{limit:1,...options});runId=run.id;notify('Generation started. Follow the run progress here.');tab('production');await refresh()}catch(e){notify(e.message,true)}}
$('advanceOnce').onclick=()=>runWorker('pipeline');$('resumePlanning').onclick=()=>runWorker('planning');$('assemble').onclick=()=>runWorker('assembly',{episode_id:$('episode').value});$('goReview').onclick=()=>tab('review');
function empty(container,text){const block=document.createElement('div');block.className='empty-state';block.textContent=text;container.append(block)}
async function loadAssets(){const [data,exportData]=await Promise.all([api(base()+'/review-assets?status='+$('assetStatus').value),api(base()+'/exports')]);$('assets').replaceChildren();$('exportsList').replaceChildren();const exports=exportData.assets;for(const asset of data.assets)assetCard(asset,$('assets'));for(const asset of exports)assetCard(asset,$('exportsList'));if(!data.assets.length)empty($('assets'),'No assets in this view. New candidates appear after generation.');if(!exports.length)empty($('exportsList'),'Finished episodes appear here after clip approval and assembly.');}
function assetCard(asset,container){
 const card=document.createElement('article');card.className='card asset-card';
 const media=document.createElement(['shot_video','final_render'].includes(asset.asset_type)?'video':'img');media.src=asset.preview_url;media.alt=labels[asset.asset_type]||'Generated asset';media.loading='lazy';if(media.tagName==='VIDEO'){media.controls=true;media.preload='metadata'}
 const title=document.createElement('h3');title.textContent=labels[asset.asset_type]||asset.asset_type;const detail=document.createElement('small');detail.textContent=`Version #${asset.id} · ${asset.entity_id||''} · ${asset.generation_model||'Local assembly'} · ${asset.status}`;card.append(media,title,detail);
 const actions=document.createElement('div');actions.className='button-row';
 for(const state of ['approved','rejected']){const b=document.createElement('button');b.className=state==='approved'?'primary':'secondary';b.textContent=state==='approved'?'Accept & use':'Reject';b.disabled=asset.status===state||Boolean(dashboard?.worker_busy);b.onclick=async()=>{b.disabled=true;try{const result=await api(base()+`/assets/${asset.id}/review`,{status:state});notify((state==='approved'?'Version accepted. You can still edit it.':'Version rejected. Use Edit / new version to revise it.')+(result.affected_assets?` ${result.affected_assets} downstream assets need review; production is paused.`:''));await loadAssets();await refresh()}catch(e){notify(e.message,true);b.disabled=false}};actions.append(b)}
 if(asset.asset_type!=='final_render'){const b=document.createElement('button');b.className='secondary';b.textContent='Edit / new version';b.disabled=Boolean(dashboard?.worker_busy);b.onclick=()=>openAssetEditor(asset).catch(e=>notify(e.message,true));actions.append(b)}
 else{const b=document.createElement('button');b.className='secondary';b.textContent='Assemble another cut';b.onclick=()=>runWorker('assembly',{episode_id:asset.entity_id});actions.append(b);const link=document.createElement('a');link.textContent='Open episode';link.href=asset.preview_url;link.target='_blank';link.rel='noopener';actions.append(link)}
 card.append(actions);container.append(card);
}
let editorAsset=null,editorJob=null,editorBase=null,editorReferences=new Set(),deletingProject=null;
async function prepareEditor(kind,options={}){
 editorBase=base();editorReferences=new Set(options.reference_upload_ids||[]);$('revisionModel').replaceChildren();const defaultOption=document.createElement('option');defaultOption.value='';defaultOption.textContent="Use the project's image model";$('revisionModel').append(defaultOption);for(const option of $('imageModel').options){if(option.value)$('revisionModel').append(option.cloneNode(true))}$('revisionModel').value=options.image_model_key||'';
 const video=kind==='shot_video';$('originalOption').hidden=video||(!editorAsset&&!options.source_asset_id);$('useOriginal').checked=Boolean(options.use_source_image);$('revisionModelLabel').hidden=video;
 $('assetEditorNote').textContent=video?'Edit the video action prompt. The local video engine renders from the approved shot frame, or one optional uploaded starting frame. To modify a frame with GPT, edit its shot image first.':'Edit the instructions, optionally modify the original image, and choose references. Generation uses your configured OpenAI API key.';
 $('referenceHelp').textContent=video?'Choose one optional uploaded starting frame. This conditions a new video; it does not edit the existing video file.':'Choose up to three uploaded images for identity, style or composition. Leave them unselected to render without extra uploads.';
 $('saveRevision').textContent=editorJob?'Save render inputs':'Queue edited version';$('renderRevision').textContent=editorJob?'Save & render this job':'Queue & render this version';$('editorNotice').textContent='';$('assetEditor').showModal();await loadReferenceLibrary();
}
async function openAssetEditor(asset){editorJob=null;editorAsset=await api(base()+`/assets/${asset.id}/edit`);$('assetEditorTitle').textContent=`Edit version #${asset.id}`;$('revisionPrompt').value=editorAsset.original_prompt||'';await prepareEditor(asset.asset_type,{use_source_image:editorAsset.can_edit_image});}
async function openJobEditor(){if(!selectedPrompt||selectedPrompt.kind==='video_plan')return;editorAsset=null;editorJob=selectedPrompt;const options=await api(base()+`/jobs/${editorJob.id}/options`);$('assetEditorTitle').textContent=`Render inputs for job #${editorJob.id}`;$('revisionPrompt').value=$('jobPrompt').value;await prepareEditor(editorJob.job_type,options);}
async function loadReferenceLibrary(){const data=await api(editorBase+'/references');$('referenceLibrary').replaceChildren();if(!data.references.length){empty($('referenceLibrary'),'No uploads yet. References are optional.');return}for(const reference of data.references){const label=document.createElement('label');label.className='reference-choice';const image=document.createElement('img');image.src=reference.preview_url;image.alt=reference.name;const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=editorReferences.has(reference.id);checkbox.onchange=()=>{const max=(editorAsset?.asset_type||editorJob?.job_type)==='shot_video'?1:3;if(checkbox.checked&&editorReferences.size>=max){checkbox.checked=false;$('editorNotice').textContent=`Choose at most ${max} reference image(s).`;return}if(checkbox.checked)editorReferences.add(reference.id);else editorReferences.delete(reference.id)};const text=document.createElement('span');text.textContent=reference.name+' · '+reference.role;label.append(image,checkbox,text);$('referenceLibrary').append(label)}}
$('referenceUpload').onchange=async()=>{const file=$('referenceUpload').files[0];if(!file)return;if(file.size>10*1024*1024){$('editorNotice').textContent='Choose an image under 10 MB.';return}const button=$('referenceUpload');button.disabled=true;try{const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Image could not be read'));reader.readAsDataURL(file)});const result=await api(editorBase+'/references',{name:file.name,data:encoded,role:$('uploadRole').value});const max=(editorAsset?.asset_type||editorJob?.job_type)==='shot_video'?1:3;if(editorReferences.size<max)editorReferences.add(result.id);await loadReferenceLibrary();$('editorNotice').textContent='Reference uploaded. Select it to include it in this render.'}catch(e){$('editorNotice').textContent=e.message}finally{button.disabled=false;button.value=''}};
async function saveEditor(render){$('saveRevision').disabled=true;$('renderRevision').disabled=true;try{const body={prompt:$('revisionPrompt').value,use_source_image:$('useOriginal').checked&&!$('originalOption').hidden,reference_upload_ids:[...editorReferences],image_model_key:$('revisionModelLabel').hidden?null:($('revisionModel').value||null)};let jobId,kind;if(editorJob){await api(editorBase+`/jobs/${editorJob.id}/options`,body,'PUT');await api(editorBase+`/jobs/${editorJob.id}/prompt`,{prompt:body.prompt},'PUT');jobId=editorJob.id;kind=editorJob.job_type;}else{const result=await api(editorBase+`/assets/${editorAsset.id}/regenerate`,body);jobId=result.id;kind=editorAsset.asset_type;}$('assetEditor').close();notify('Render inputs saved. Original versions are preserved.');if(render){const run=await api(editorBase+'/workers/'+(kind==='shot_video'?'comfy-videos':'openai-references'),{limit:1,job_id:jobId});runId=run.id;tab('production');}else tab('prompts');await refresh();}catch(e){$('editorNotice').textContent=e.message;notify(e.message,true)}finally{$('saveRevision').disabled=false;$('renderRevision').disabled=false}}
$('saveRevision').onclick=()=>saveEditor(false);$('renderRevision').onclick=()=>saveEditor(true);$('closeEditor').onclick=()=>$('assetEditor').close();$('promptReferences').onclick=()=>openJobEditor().catch(e=>notify(e.message,true));$('renderPrompt').onclick=()=>{if(selectedPrompt)runWorker(selectedPrompt.job_type==='shot_video'?'comfy-videos':'openai-references',{job_id:selectedPrompt.id})};
$('deleteProject').onclick=async()=>{try{const info=await api(base()+'/delete-preview');deletingProject=$('project').value;$('deleteDetails').textContent=`Delete “${info.project_id}”? ${info.jobs||0} jobs and ${info.assets||0} asset versions. Output folder: ${info.folder}`;$('confirmDelete').textContent='Yes, delete production';$('deleteDialog').showModal()}catch(e){notify(e.message,true)}};
$('cancelDelete').onclick=()=>$('deleteDialog').close();$('confirmDelete').onclick=async()=>{const button=$('confirmDelete');button.disabled=true;try{const result=await api('/projects/'+encodeURIComponent(deletingProject),{confirm_project_id:deletingProject},'DELETE');if(!result.cleanup_complete){$('deleteDetails').textContent='Database records were deleted, but file cleanup is pending. Retry to finish removing this project’s files.';button.textContent='Retry file cleanup';return}$('deleteDialog').close();runId=null;selectedPrompt=null;dashboard=null;latestReviewSignature='';await loadProjects();notify('Production deleted. Its project records, media, uploads and run logs were cleaned.');if(!$('project').value)$('newProject').click()}catch(e){notify(e.message,true);$('deleteDetails').textContent=e.message}finally{button.disabled=false}};
$('assetStatus').onchange=()=>loadAssets().catch(e=>notify(e.message,true));
$('project').onchange=()=>{runId=null;selectedPrompt=null;latestReviewSignature='';notify('');refresh();tab('production')};$('refresh').onclick=()=>{latestReviewSignature='';refresh()};
async function poll(){if(runId){try{const run=await api('/runs/'+runId);$('runLabel').textContent=`${run.worker} · ${run.status}`;$('runLog').textContent=run.output||'Waiting for the worker…';if(run.status!=='running'){runId=null;await refresh();if(run.status==='failed')notify('The worker stopped. Expand the generation log for the cause.',true);}}catch(e){runId=null;notify(e.message,true)}}await refresh()}
async function initialize(){runtime();try{const health=await api('/health');$('connection').textContent=health.ok?'Gateway connected':'Check gateway';const models=await api('/models');$('imageModel').replaceChildren();for(const model of models.models.filter(m=>m.model_type==='image'&&m.backend==='openai_api')){const option=document.createElement('option');option.value=model.model_key;option.textContent=model.display_name||model.model_key;$('imageModel').append(option)}if(models.default_image_model)$('imageModel').value=models.default_image_model;await loadProjects();if($('project').value)tab('production');}catch(e){$('connection').textContent='Connection needs attention';notify(e.message,true)}try{const options=await api('/video-options');$('loraNote').textContent=options.note;for(const name of options.loras){const option=document.createElement('option');option.value=option.textContent=name;$('loraName').append(option)}}catch(e){$('loraNote').textContent='ComfyUI options are unavailable.'}}
initialize();setInterval(poll,4000);
